name: CI/CD Pipeline

on:
  push:
    branches: [ simple_core ]  # Run on pushes to the main branch
  pull_request:  # Optionally run on pull requests

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu virtual environment
    strategy:
      fail-fast: false  # Allow all steps to run even if one fails (optional)
    steps:
      - uses: actions/checkout@v3  # Checkout code from the repository
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.8  # Adjust based on your Python requirements

      - name: Install dependencies
        run: |
          sudo apt install python3-virtualenv
          virtualenv env
          source env/bin/activate
          pip3 install langchain streamlit streamlit_chat chromadb pypdf fastembed pytest

      - name: Install Ollama (adjust if using a different package manager)
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Pull Ollama mistral model
        run: |
          ollama pull mistral
          
      - name: Run Super-Linter (highly recommended)
        uses: github/super-linter@v4

      - name: Run unit tests
        run: pytest  # Replace with your specific test commands if needed

      - name: Build Streamlit app (if applicable)
        run: |
          streamlit run server.py  # Adjust the command if needed
   lint:
    steps:
      - name: Check GITHUB_TOKEN
        run: echo ${{ secrets.GITHUB_TOKEN }}
